management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: actuator,beans,env,openapi,swagger-ui,health,info,metrics
  health:
    db:
      enabled: true
  endpoint:
    beans:
      enabled: true
    env:
      enabled: true
      show-values: when-authorized
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  info:
    git:
      mode: full
    build:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
org:
  techbd:    
    service:
      http:
        hub:
          prime:
            csv:
              # Specifies the CSV validation strategy.
              # Options:
              # - pythonExecutor: Executes a Python script locally for validation.
              # - pythonService: Uses a remote Python-based validation service.
              validator: pythonExecutor  # Options: pythonExecutor, pythonService
              validation:
                pythonScriptPath: ${TECHBD_CSV_PYTHON_SCRIPT_PATH:../support/specifications/flat-file/validate-nyher-fhir-ig-equivalent.py}
                pythonExecutable: ${TECHBD_CSV_PYTHON_EXECUTABLE:python3}
                packagePath: ${TECHBD_CSV_PACKAGE_PATH:../support/specifications/flat-file/datapackage-nyher-fhir-ig-equivalent.json}
                inboundPath: ${TECHBD_CSV_INBOUND_PATH:/app/techbyDesign/flatFile/inbound}
                outputPath: ${TECHBD_CSV_INBOUND_PATH:/app/techbyDesign/flatFile/outbound}
                ingessHomePath: ${TECHBD_CSV_INGRESS_PATH:/app/techbyDesign/flatFile/ingress}   
            csvs:  
              # Base URL for the remote CSV validation service.
              baseUrl: https://synthetic.csv-frictionless-validator.techbd.org
              # API endpoint for CSV validation.
              endpoint: /validate_service_nyher_fhir_ig_equivalent/