# when using environment variables, use this pattern:
# `${${SPRING_PROFILES_ACTIVE}_TECHBD_xyz_abc_def:}`
# - sandbox_TECHBD_xyz_abc_def
# - devl_TECHBD_xyz_abc_def
# - stage_TECHBD_xyz_abc_def
# - prod_TECHBD_xyz_abc_def

logging:
  level:
    org:
      springframework: INFO
      hibernate: ERROR
      techbd:
        service:
          http:
            hub:
              prime:
                api: INFO
    ca:
      uhn: WARN
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: techbd-hub-prime
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 81bdb4df5dbf13
    password: 8d8fbb25e43ffc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2MB

springdoc:
  api-docs:
    path: /docs/api/openapi
  swagger-ui.path: /docs/api/interactive/index.html
  swagger-ui:
    doc-expansion: none
  show-actuator: true 

server:
  servlet:
    context-path: /
    session:
      cookie:
        secure: true
        http-only: true
        same-site: LAX 

org:
  techbd:
    # these should be setup in ENV vars, not here
    # orchestrate:
    #   sftp:
    #     account:
    #       orchctlts:
    #         - tenantId: name1
    #           server: sftp.techbd.org
    #           port: 22
    #           username: name1
    #           password: password
    #         - tenantId: name2
    #           server: sftp.techbd.org
    #           port: 22
    #           username: name2
    #           password: password
    service:
      http:
        hub:
          prime:
            csv:
              validation:
                python-script-path: ${TECHBD_CSV_PYTHON_SCRIPT_PATH:src/main/java/org/techbd/csvvalidator/csv-validate.py}
                python-executable: ${TECHBD_CSV_PYTHON_EXECUTABLE:python3}
                package-path: ${TECHBD_CSV_PACKAGE_PATH:src/main/java/org/techbd/csvvalidator/datapackage-ig.json}
                output-path: ${TECHBD_CSV_OUTPUT_PATH:src/main/java/org/techbd/csvvalidator/output/output.json}
                file1: ${TECHBD_CSV_FILE1_PATH:src/main/java/org/techbd/csvvalidator/data/QE_ADMIN_DATA.csv}
                file2: ${TECHBD_CSV_FILE2_PATH:src/main/java/org/techbd/csvvalidator/data/SCREENING_OBSERVATION_DATA.csv}
                file3: ${TECHBD_CSV_FILE3_PATH:src/main/java/org/techbd/csvvalidator/data/SCREENING_LOCATION_DATA.csv}
                file4: ${TECHBD_CSV_FILE4_PATH:src/main/java/org/techbd/csvvalidator/data/SCREENING_ENCOUNTER_DATA.csv}
                file5: ${TECHBD_CSV_FILE5_PATH:src/main/java/org/techbd/csvvalidator/data/SCREENING_CONSENT_DATA.csv}
                file6: ${TECHBD_CSV_FILE6_PATH:src/main/java/org/techbd/csvvalidator/data/SCREENING_RESOURCES_DATA.csv}
                file7: ${TECHBD_CSV_FILE7_PATH:src/main/java/org/techbd/csvvalidator/data/DEMOGRAPHIC_DATA.csv}
            version: @project.version@
            fhirVersion: r4
            igVersion: 1.1.0
            igPackages:
                fhir-v4:
                    # Path to SHIN-NY IG package downloaded from URL: https://shinny.org/us/ny/hrsn/downloads.html
                    shinNy: ig-packages/shin-ny-ig/v${org.techbd.service.http.hub.prime.igVersion}
                    # Path to US Core IG: package downloaded from URL: https://hl7.org/fhir/us/core/STU7/downloads.html
                    usCore: ig-packages/fhir-v4/us-core/stu-7.0.0
                    # Path to SDOH Clinical Care IG package downloaded from URL: https://hl7.org/fhir/us/sdoh-clinicalcare/downloads.html
                    sdoh: ig-packages/fhir-v4/sdoh-clinicalcare/stu-2.2.0
                    # Path to UV-SDC IG package downloaded from URL: https://hl7.org/fhir/uv/sdc/downloads.html
                    uvSdc: ig-packages/fhir-v4/uv-sdc/stu-3.0.0
            defaultSdohFhirProfileUrl: https://shinny.org/us/ny/hrsn/StructureDefinition-SHINNYBundleProfile.json
            defaultDatalakeApiUrl: https://uzrlhp39e0.execute-api.us-east-1.amazonaws.com/dev/HRSNBundle
            fhirUmlsApiKey: umls_api_key
        interactions:
          defaultPersistStrategy: "{ \"nature\": \"fs\" }"
          persist:
            db:
              uri-matcher:
                # TODO: figure out why this is not being read in InteractionsFilter
                regex:
                  - .*
                  - [^/Bundle/.*, POST, persistReqPayload persistRespPayload]         
          saveUserDataToInteractions: true
    udi:
      prime:
        jdbc: 
          # the reason `url` and `jdbcUrl` are both supplied is that some poolers
          # like `url` while others (e.g. Hikari, the default) like `jdbcUrl`
          url: ${${SPRING_PROFILES_ACTIVE}_TECHBD_UDI_DS_PRIME_JDBC_URL:}
          jdbcUrl: ${${SPRING_PROFILES_ACTIVE}_TECHBD_UDI_DS_PRIME_JDBC_URL:}
          username: ${${SPRING_PROFILES_ACTIVE}_TECHBD_UDI_DS_PRIME_JDBC_USERNAME:}
          password: ${${SPRING_PROFILES_ACTIVE}_TECHBD_UDI_DS_PRIME_JDBC_PASSWORD:}
          driverClassName: org.postgresql.Driver
          maximumPoolSize: 50
          minimumIdle: 5
          idleTimeout: 300000
          connectionTimeout: 30000
          maxLifetime: 1800000
   